### PR TITLE
add probes for GnuTLS 3.6.8

### PR DESCRIPTION
**Pull request by nmav**

### CODE REVIEW

**Comment by tomato42** [comment]
Looks good, could you also add configuration with client certificates _disabled_ ? As that is the most common configuration for Internet servers, having probe with CR will likely cause false negatives

Compare [this](https://github.com/WestpointLtd/tls_prober/blob/master/fingerprints/gnutls-324.fp) with [this](https://github.com/WestpointLtd/tls_prober/blob/master/fingerprints/gnutls-324-disable-cert-request.fp). For consistent fingerprints across versions I've been using configurations described in [SERVER_CONFIGURATION.md](https://github.com/WestpointLtd/tls_prober/blob/master/SERVER_CONFIGURATION.md)

**Comment by nmav** [comment]
Done. I've also added a run on mod_gnutls with apache which seems to provide a very different signature.

**Comment by tomato42** [comment]
that different signature seems to be caused by fewer ciphers being enabled and TLS 1.0 support disabled...

was mod_gnutls and apache compiled from source, or were those Fedora packages?

**Comment by nmav** [comment]
It's the fedora package.

**Comment by tomato42** [comment]
then the exact n-v-r's should be included in the description, as in, for example, https://github.com/WestpointLtd/tls_prober/blob/master/fingerprints/gnutls-28519el67-rhel-6.fp

**Comment by nmav** [comment]
Done

**Comment by tomato42** [comment]
merged with minor tweak to description

Thanks!

**Pull request merged**
